"""DEM mesh interpolation, RF surface hits and terrain occlusion."""
from pathlib import Path

import numpy as np
import pytest

from airsim_rf.terrain import TerrainGrid, demo_terrain
from airsim_rf.scattering import FirstOrderScatteringPathSolver


def test_demo_relief_and_scripted_terrain_clearance():
    terrain = demo_terrain()
    assert terrain.heights_m.min() == 0
    assert terrain.heights_m.max() == pytest.approx(30)
    assert np.count_nonzero(terrain.heights_m == 0) > 1
    # A known planar slope verifies both geometric clearance and Doppler velocity.
    ramp = TerrainGrid([0, 10], [0, 10], [[0, 10], [20, 30]])
    positions, velocities = ramp.clearance_pose([[2, 3, 1], [2, 3, 40]],
                                               [[3, 4, 0], [3, 4, 2]], clearance_m=5)
    np.testing.assert_allclose(positions, [[2, 3, 13], [2, 3, 40]])
    np.testing.assert_allclose(velocities, [[3, 4, 11], [3, 4, 2]])
    starts = np.array([[-60,-30,12], [45,45,18], [-30,-10,14], [30,-50,20]])
    motion = np.array([[2,0,0], [-1,0,0], [3,0,0], [0,3,0]])
    for epoch in np.linspace(0, 5.5, 201):
        p, v = terrain.clearance_pose(starts+epoch*motion, motion)
        assert np.min(p[:,2]-terrain.elevation_at(p[:,0], p[:,1])) >= 5-1e-12
        np.testing.assert_array_equal(v[:,:2], motion[:,:2])


def test_triangle_interpolation_and_invalid_dem():
    grid = TerrainGrid([0, 10], [0, 10], [[0, 0], [0, 10]])
    # The diagonal is a ridge; bilinear interpolation would give 2.5 here.
    assert grid.elevation_at(5, 5) == pytest.approx(5)
    assert grid.elevation_at(8, 2) == pytest.approx(2)
    assert grid.elevation_at(2, 8) == pytest.approx(2)
    assert grid.elevation_at(10, 10) == pytest.approx(10)
    with pytest.raises(ValueError, match='outside'):
        grid.elevation_at(11, 0)
    with pytest.raises(ValueError, match='increasing'):
        TerrainGrid([0, 0], [0, 1], [[0, 0], [0, 0]])
    with pytest.raises(ValueError, match='finite'):
        TerrainGrid([0, 1], [0, 1], [[0, np.nan], [0, 0]])


def test_exported_dem_has_correct_winding_and_actual_rf_hit_elevation(tmp_path):
    import sionna.rt as rt
    import mitsuba as mi
    terrain = demo_terrain()
    vertices, faces = terrain.mesh()
    assert (len(vertices), len(faces)) == (441, 800)
    normals = np.cross(vertices[faces[:, 1]]-vertices[faces[:, 0]], vertices[faces[:, 2]]-vertices[faces[:, 0]])
    assert (normals[:, 2] > 0).all()
    path = tmp_path/'terrain.ply'
    terrain.write_ply(path)
    scene = rt.load_scene(str(Path(__file__).resolve().parents[1]/'benchmarks/scenes/terrain.xml'))
    for x, y in ((-41, -23), (7, 13), (54, 46)):
        hit = scene.mi_scene.ray_intersect(mi.Ray3f(mi.Point3f(x, y, 40), mi.Vector3f(0, 0, -1)))
        assert bool(hit.is_valid()[0])
        assert float(hit.p.z[0]) == pytest.approx(float(terrain.elevation_at(x, y)), abs=3e-6)
    # Fixture is generated by the same API exposed to callers.
    assert path.read_bytes() == (Path(__file__).resolve().parents[1]/'benchmarks/scenes/terrain.ply').read_bytes()


def test_dem_scattered_paths_follow_surface_and_bistatic_delay():
    import sionna.rt as rt
    from sionna.rt.constants import InteractionType
    scene = rt.load_scene(str(Path(__file__).resolve().parents[1]/'benchmarks/scenes/terrain.xml'))
    scene.tx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='tr38901', polarization='V')
    scene.rx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='tr38901', polarization='V')
    tx, rx = np.array([0, 0, 40]), np.array([10, -5, 45])
    scene.add(rt.Transmitter('tx', position=tx.tolist(), orientation=[0, np.pi/2, 0]))
    scene.add(rt.Receiver('rx', position=rx.tolist(), orientation=[0, np.pi/2, 0]))
    solver = FirstOrderScatteringPathSolver()
    # Zero-height patches merge coplanar triangles into fewer specular planes.
    assert 0 < solver.specular_plane_count(scene) <= len(demo_terrain().mesh()[1])
    paths = solver(scene, samples_per_src=1028, max_num_paths_per_src=1829)
    diffuse = paths.interactions.numpy()[0, 0, 0] == int(InteractionType.DIFFUSE)
    points = paths.vertices.numpy()[0, 0, 0][diffuse]
    assert len(points) > 0
    assert np.std(points[:, 2]) > .5
    np.testing.assert_allclose(points[:, 2], demo_terrain().elevation_at(points[:, 0], points[:, 1]), atol=2e-5)
    a, tau = paths.cir(normalize_delays=False, out_type='numpy')
    expected = (np.linalg.norm(points-tx, axis=1)+np.linalg.norm(points-rx, axis=1))/299792458.
    np.testing.assert_allclose(tau[0, 0, diffuse], expected, rtol=2e-6)
    assert np.isfinite(a).all()


def test_dem_ridge_blocks_direct_path(tmp_path):
    import sionna.rt as rt
    fixture = Path(__file__).resolve().parents[1]/'benchmarks/scenes/ground.xml'
    counts = []
    for name, heights in (('flat', [[0, 0, 0], [0, 0, 0]]), ('ridge', [[0, 6, 0], [0, 6, 0]])):
        mesh = tmp_path/f'{name}.ply'
        TerrainGrid([-10, 0, 10], [-10, 10], heights).write_ply(mesh)
        xml = tmp_path/f'{name}.xml'
        xml.write_text(fixture.read_text().replace('ground.ply', mesh.name))
        scene = rt.load_scene(str(xml))
        scene.tx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='iso', polarization='V')
        scene.rx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='iso', polarization='V')
        scene.add(rt.Transmitter('tx', position=[-8, 0, 2]))
        scene.add(rt.Receiver('rx', position=[8, 0, 2]))
        paths = FirstOrderScatteringPathSolver()(scene, max_depth=0, diffuse_reflection=False,
                                                specular_reflection=False, max_num_paths_per_src=1)
        _, tau = paths.cir(normalize_delays=False, out_type='numpy')
        counts.append(int((tau >= 0).sum()))
    assert counts == [1, 0]


def test_benchmark_mesh_is_immutable_and_matches_historical_grid():
    from hashlib import sha256
    from airsim_rf.terrain import demo_terrain, scene_provenance, validate_flight_envelope
    root = Path(__file__).resolve().parents[1]
    mesh = root/'benchmarks/scenes/terrain_benchmark_v1.ply'
    assert sha256(mesh.read_bytes()).hexdigest() == 'db07f14ad075a12b204c9c5115e60aae314bfd044d97965c4bc524d3d7630f3b'
    lines = mesh.read_text().split('end_header\n')[1].splitlines()
    vertices, faces = demo_terrain(historical=True).mesh()
    np.testing.assert_allclose(np.array([list(map(float,line.split())) for line in lines[:len(vertices)]]), vertices, atol=5e-8)
    contract = scene_provenance(root/'benchmarks/scenes/terrain_benchmark_v1.xml')
    assert contract['meshes_sha256'][mesh.name] == sha256(mesh.read_bytes()).hexdigest()
    valid = validate_flight_envelope(demo_terrain(historical=True), np.array([[0,0,10.]]), np.array([[1,0,0.]]), .5)
    assert valid['minimum_clearance_bound_m'] > 1
    with pytest.raises(ValueError, match='clearance'):
        validate_flight_envelope(demo_terrain(), np.array([[0,0,10.]]), np.array([[1,0,0.]]), .5)
    with pytest.raises(ValueError, match='leaves'):
        validate_flight_envelope(demo_terrain(historical=True), np.array([[99,0,40.]]), np.array([[3,0,0.]]), 1)
