"""DEM mesh interpolation, RF surface hits and terrain occlusion."""
from pathlib import Path

import numpy as np
import pytest

from airsim_rf.terrain import TerrainGrid, demo_terrain
from airsim_rf.scattering import FirstOrderScatteringPathSolver


def test_triangle_interpolation_and_invalid_dem():
    grid = TerrainGrid([0, 10], [0, 10], [[0, 0], [0, 10]])
    # The diagonal is a ridge; bilinear interpolation would give 2.5 here.
    assert grid.elevation_at(5, 5) == pytest.approx(5)
    assert grid.elevation_at(8, 2) == pytest.approx(2)
    assert grid.elevation_at(2, 8) == pytest.approx(2)
    assert grid.elevation_at(10, 10) == pytest.approx(10)
    with pytest.raises(ValueError, match='outside'):
        grid.elevation_at(11, 0)
    with pytest.raises(ValueError, match='increasing'):
        TerrainGrid([0, 0], [0, 1], [[0, 0], [0, 0]])
    with pytest.raises(ValueError, match='finite'):
        TerrainGrid([0, 1], [0, 1], [[0, np.nan], [0, 0]])


def test_exported_dem_has_correct_winding_and_actual_rf_hit_elevation(tmp_path):
    import sionna.rt as rt
    import mitsuba as mi
    terrain = demo_terrain()
    vertices, faces = terrain.mesh()
    assert (len(vertices), len(faces)) == (441, 800)
    normals = np.cross(vertices[faces[:, 1]]-vertices[faces[:, 0]], vertices[faces[:, 2]]-vertices[faces[:, 0]])
    assert (normals[:, 2] > 0).all()
    path = tmp_path/'terrain.ply'
    terrain.write_ply(path)
    scene = rt.load_scene(str(Path(__file__).resolve().parents[1]/'benchmarks/scenes/terrain.xml'))
    for x, y in ((-41, -23), (7, 13), (54, 46)):
        hit = scene.mi_scene.ray_intersect(mi.Ray3f(mi.Point3f(x, y, 20), mi.Vector3f(0, 0, -1)))
        assert bool(hit.is_valid()[0])
        assert float(hit.p.z[0]) == pytest.approx(float(terrain.elevation_at(x, y)), abs=3e-6)
    # Fixture is generated by the same API exposed to callers.
    assert path.read_bytes() == (Path(__file__).resolve().parents[1]/'benchmarks/scenes/terrain.ply').read_bytes()


def test_dem_scattered_paths_follow_surface_and_bistatic_delay():
    import sionna.rt as rt
    from sionna.rt.constants import InteractionType
    scene = rt.load_scene(str(Path(__file__).resolve().parents[1]/'benchmarks/scenes/terrain.xml'))
    scene.tx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='tr38901', polarization='V')
    scene.rx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='tr38901', polarization='V')
    tx, rx = np.array([0, 0, 10]), np.array([10, -5, 15])
    scene.add(rt.Transmitter('tx', position=tx.tolist(), orientation=[0, np.pi/2, 0]))
    scene.add(rt.Receiver('rx', position=rx.tolist(), orientation=[0, np.pi/2, 0]))
    solver = FirstOrderScatteringPathSolver()
    assert solver.specular_plane_count(scene) == 800
    paths = solver(scene, samples_per_src=1028, max_num_paths_per_src=1829)
    diffuse = paths.interactions.numpy()[0, 0, 0] == int(InteractionType.DIFFUSE)
    points = paths.vertices.numpy()[0, 0, 0][diffuse]
    assert len(points) > 700
    assert np.std(points[:, 2]) > .5
    np.testing.assert_allclose(points[:, 2], demo_terrain().elevation_at(points[:, 0], points[:, 1]), atol=2e-5)
    a, tau = paths.cir(normalize_delays=False, out_type='numpy')
    expected = (np.linalg.norm(points-tx, axis=1)+np.linalg.norm(points-rx, axis=1))/299792458.
    np.testing.assert_allclose(tau[0, 0, diffuse], expected, rtol=2e-6)
    assert np.isfinite(a).all()


def test_dem_ridge_blocks_direct_path(tmp_path):
    import sionna.rt as rt
    fixture = Path(__file__).resolve().parents[1]/'benchmarks/scenes/ground.xml'
    counts = []
    for name, heights in (('flat', [[0, 0, 0], [0, 0, 0]]), ('ridge', [[0, 6, 0], [0, 6, 0]])):
        mesh = tmp_path/f'{name}.ply'
        TerrainGrid([-10, 0, 10], [-10, 10], heights).write_ply(mesh)
        xml = tmp_path/f'{name}.xml'
        xml.write_text(fixture.read_text().replace('ground.ply', mesh.name))
        scene = rt.load_scene(str(xml))
        scene.tx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='iso', polarization='V')
        scene.rx_array = rt.PlanarArray(num_rows=1, num_cols=1, pattern='iso', polarization='V')
        scene.add(rt.Transmitter('tx', position=[-8, 0, 2]))
        scene.add(rt.Receiver('rx', position=[8, 0, 2]))
        paths = FirstOrderScatteringPathSolver()(scene, max_depth=0, diffuse_reflection=False,
                                                specular_reflection=False, max_num_paths_per_src=1)
        _, tau = paths.cir(normalize_delays=False, out_type='numpy')
        counts.append(int((tau >= 0).sum()))
    assert counts == [1, 0]
