# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import squall_rf_pb2 as squall__rf__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in squall_rf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SquallRfControlStub:
    """The primary control interface for Squall RF pipelines.
    This provides a simplified backend API that the C++ MEL implementation translates
    complex GRA/UCI commands into.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/squall.rf.control.v1.SquallRfControl/GetStatus',
                request_serializer=squall__rf__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=squall__rf__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.AddDataDestination = channel.unary_unary(
                '/squall.rf.control.v1.SquallRfControl/AddDataDestination',
                request_serializer=squall__rf__pb2.AddDataDestinationRequest.SerializeToString,
                response_deserializer=squall__rf__pb2.AddDataDestinationResponse.FromString,
                _registered_method=True)
        self.RemoveDataDestination = channel.unary_unary(
                '/squall.rf.control.v1.SquallRfControl/RemoveDataDestination',
                request_serializer=squall__rf__pb2.RemoveDataDestinationRequest.SerializeToString,
                response_deserializer=squall__rf__pb2.RemoveDataDestinationResponse.FromString,
                _registered_method=True)
        self.TuneRf = channel.unary_unary(
                '/squall.rf.control.v1.SquallRfControl/TuneRf',
                request_serializer=squall__rf__pb2.TuneRfRequest.SerializeToString,
                response_deserializer=squall__rf__pb2.TuneRfResponse.FromString,
                _registered_method=True)
        self.CommandRf = channel.unary_unary(
                '/squall.rf.control.v1.SquallRfControl/CommandRf',
                request_serializer=squall__rf__pb2.CommandRfRequest.SerializeToString,
                response_deserializer=squall__rf__pb2.CommandRfResponse.FromString,
                _registered_method=True)


class SquallRfControlServicer:
    """The primary control interface for Squall RF pipelines.
    This provides a simplified backend API that the C++ MEL implementation translates
    complex GRA/UCI commands into.
    """

    def GetStatus(self, request, context):
        """Query the live status of the pipeline (maps to RF MonitorMEL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDataDestination(self, request, context):
        """Dynamically register a new UDP destination for the data stream (Data Plane negotiation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDataDestination(self, request, context):
        """Explicitly unregister a dynamic UDP destination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TuneRf(self, request, context):
        """Send a dynamic tuning command to an active RF pipeline (maps to RF C2MEL JobRequests)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandRf(self, request, context):
        """Send a state command to the active RF pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SquallRfControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=squall__rf__pb2.GetStatusRequest.FromString,
                    response_serializer=squall__rf__pb2.GetStatusResponse.SerializeToString,
            ),
            'AddDataDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDataDestination,
                    request_deserializer=squall__rf__pb2.AddDataDestinationRequest.FromString,
                    response_serializer=squall__rf__pb2.AddDataDestinationResponse.SerializeToString,
            ),
            'RemoveDataDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDataDestination,
                    request_deserializer=squall__rf__pb2.RemoveDataDestinationRequest.FromString,
                    response_serializer=squall__rf__pb2.RemoveDataDestinationResponse.SerializeToString,
            ),
            'TuneRf': grpc.unary_unary_rpc_method_handler(
                    servicer.TuneRf,
                    request_deserializer=squall__rf__pb2.TuneRfRequest.FromString,
                    response_serializer=squall__rf__pb2.TuneRfResponse.SerializeToString,
            ),
            'CommandRf': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandRf,
                    request_deserializer=squall__rf__pb2.CommandRfRequest.FromString,
                    response_serializer=squall__rf__pb2.CommandRfResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'squall.rf.control.v1.SquallRfControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('squall.rf.control.v1.SquallRfControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SquallRfControl:
    """The primary control interface for Squall RF pipelines.
    This provides a simplified backend API that the C++ MEL implementation translates
    complex GRA/UCI commands into.
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/squall.rf.control.v1.SquallRfControl/GetStatus',
            squall__rf__pb2.GetStatusRequest.SerializeToString,
            squall__rf__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDataDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/squall.rf.control.v1.SquallRfControl/AddDataDestination',
            squall__rf__pb2.AddDataDestinationRequest.SerializeToString,
            squall__rf__pb2.AddDataDestinationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDataDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/squall.rf.control.v1.SquallRfControl/RemoveDataDestination',
            squall__rf__pb2.RemoveDataDestinationRequest.SerializeToString,
            squall__rf__pb2.RemoveDataDestinationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TuneRf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/squall.rf.control.v1.SquallRfControl/TuneRf',
            squall__rf__pb2.TuneRfRequest.SerializeToString,
            squall__rf__pb2.TuneRfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandRf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/squall.rf.control.v1.SquallRfControl/CommandRf',
            squall__rf__pb2.CommandRfRequest.SerializeToString,
            squall__rf__pb2.CommandRfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
